// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/display (interfaces: FrameMetadataBuilder,ExposureSettingsBuilder,CameraModesBuilder,CustomFunctionsBuilder,ThumbnailBuilder,DisplayableFrameBuilder)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/builder_mock.go -package=display_test github.com/ma-tf/meta1v/internal/service/display FrameMetadataBuilder,ExposureSettingsBuilder,CameraModesBuilder,CustomFunctionsBuilder,ThumbnailBuilder,DisplayableFrameBuilder
//

// Package display_test is a generated GoMock package.
package display_test

import (
	context "context"
	reflect "reflect"

	display "github.com/ma-tf/meta1v/internal/service/display"
	records "github.com/ma-tf/meta1v/pkg/records"
	gomock "go.uber.org/mock/gomock"
)

// MockFrameMetadataBuilder is a mock of FrameMetadataBuilder interface.
type MockFrameMetadataBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockFrameMetadataBuilderMockRecorder
	isgomock struct{}
}

// MockFrameMetadataBuilderMockRecorder is the mock recorder for MockFrameMetadataBuilder.
type MockFrameMetadataBuilderMockRecorder struct {
	mock *MockFrameMetadataBuilder
}

// NewMockFrameMetadataBuilder creates a new mock instance.
func NewMockFrameMetadataBuilder(ctrl *gomock.Controller) *MockFrameMetadataBuilder {
	mock := &MockFrameMetadataBuilder{ctrl: ctrl}
	mock.recorder = &MockFrameMetadataBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFrameMetadataBuilder) EXPECT() *MockFrameMetadataBuilderMockRecorder {
	return m.recorder
}

// WithFrameMetadata mocks base method.
func (m *MockFrameMetadataBuilder) WithFrameMetadata(ctx context.Context, r records.EFRM) display.ExposureSettingsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithFrameMetadata", ctx, r)
	ret0, _ := ret[0].(display.ExposureSettingsBuilder)
	return ret0
}

// WithFrameMetadata indicates an expected call of WithFrameMetadata.
func (mr *MockFrameMetadataBuilderMockRecorder) WithFrameMetadata(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithFrameMetadata", reflect.TypeOf((*MockFrameMetadataBuilder)(nil).WithFrameMetadata), ctx, r)
}

// MockExposureSettingsBuilder is a mock of ExposureSettingsBuilder interface.
type MockExposureSettingsBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockExposureSettingsBuilderMockRecorder
	isgomock struct{}
}

// MockExposureSettingsBuilderMockRecorder is the mock recorder for MockExposureSettingsBuilder.
type MockExposureSettingsBuilderMockRecorder struct {
	mock *MockExposureSettingsBuilder
}

// NewMockExposureSettingsBuilder creates a new mock instance.
func NewMockExposureSettingsBuilder(ctrl *gomock.Controller) *MockExposureSettingsBuilder {
	mock := &MockExposureSettingsBuilder{ctrl: ctrl}
	mock.recorder = &MockExposureSettingsBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExposureSettingsBuilder) EXPECT() *MockExposureSettingsBuilderMockRecorder {
	return m.recorder
}

// WithExposureSettings mocks base method.
func (m *MockExposureSettingsBuilder) WithExposureSettings(ctx context.Context) display.CameraModesBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithExposureSettings", ctx)
	ret0, _ := ret[0].(display.CameraModesBuilder)
	return ret0
}

// WithExposureSettings indicates an expected call of WithExposureSettings.
func (mr *MockExposureSettingsBuilderMockRecorder) WithExposureSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithExposureSettings", reflect.TypeOf((*MockExposureSettingsBuilder)(nil).WithExposureSettings), ctx)
}

// MockCameraModesBuilder is a mock of CameraModesBuilder interface.
type MockCameraModesBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockCameraModesBuilderMockRecorder
	isgomock struct{}
}

// MockCameraModesBuilderMockRecorder is the mock recorder for MockCameraModesBuilder.
type MockCameraModesBuilderMockRecorder struct {
	mock *MockCameraModesBuilder
}

// NewMockCameraModesBuilder creates a new mock instance.
func NewMockCameraModesBuilder(ctrl *gomock.Controller) *MockCameraModesBuilder {
	mock := &MockCameraModesBuilder{ctrl: ctrl}
	mock.recorder = &MockCameraModesBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCameraModesBuilder) EXPECT() *MockCameraModesBuilderMockRecorder {
	return m.recorder
}

// WithCameraModesAndFlashInfo mocks base method.
func (m *MockCameraModesBuilder) WithCameraModesAndFlashInfo(ctx context.Context) display.CustomFunctionsBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCameraModesAndFlashInfo", ctx)
	ret0, _ := ret[0].(display.CustomFunctionsBuilder)
	return ret0
}

// WithCameraModesAndFlashInfo indicates an expected call of WithCameraModesAndFlashInfo.
func (mr *MockCameraModesBuilderMockRecorder) WithCameraModesAndFlashInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCameraModesAndFlashInfo", reflect.TypeOf((*MockCameraModesBuilder)(nil).WithCameraModesAndFlashInfo), ctx)
}

// MockCustomFunctionsBuilder is a mock of CustomFunctionsBuilder interface.
type MockCustomFunctionsBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockCustomFunctionsBuilderMockRecorder
	isgomock struct{}
}

// MockCustomFunctionsBuilderMockRecorder is the mock recorder for MockCustomFunctionsBuilder.
type MockCustomFunctionsBuilderMockRecorder struct {
	mock *MockCustomFunctionsBuilder
}

// NewMockCustomFunctionsBuilder creates a new mock instance.
func NewMockCustomFunctionsBuilder(ctrl *gomock.Controller) *MockCustomFunctionsBuilder {
	mock := &MockCustomFunctionsBuilder{ctrl: ctrl}
	mock.recorder = &MockCustomFunctionsBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomFunctionsBuilder) EXPECT() *MockCustomFunctionsBuilderMockRecorder {
	return m.recorder
}

// WithCustomFunctionsAndFocusPoints mocks base method.
func (m *MockCustomFunctionsBuilder) WithCustomFunctionsAndFocusPoints(ctx context.Context) display.ThumbnailBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithCustomFunctionsAndFocusPoints", ctx)
	ret0, _ := ret[0].(display.ThumbnailBuilder)
	return ret0
}

// WithCustomFunctionsAndFocusPoints indicates an expected call of WithCustomFunctionsAndFocusPoints.
func (mr *MockCustomFunctionsBuilderMockRecorder) WithCustomFunctionsAndFocusPoints(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithCustomFunctionsAndFocusPoints", reflect.TypeOf((*MockCustomFunctionsBuilder)(nil).WithCustomFunctionsAndFocusPoints), ctx)
}

// MockThumbnailBuilder is a mock of ThumbnailBuilder interface.
type MockThumbnailBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockThumbnailBuilderMockRecorder
	isgomock struct{}
}

// MockThumbnailBuilderMockRecorder is the mock recorder for MockThumbnailBuilder.
type MockThumbnailBuilderMockRecorder struct {
	mock *MockThumbnailBuilder
}

// NewMockThumbnailBuilder creates a new mock instance.
func NewMockThumbnailBuilder(ctrl *gomock.Controller) *MockThumbnailBuilder {
	mock := &MockThumbnailBuilder{ctrl: ctrl}
	mock.recorder = &MockThumbnailBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThumbnailBuilder) EXPECT() *MockThumbnailBuilderMockRecorder {
	return m.recorder
}

// WithThumbnail mocks base method.
func (m *MockThumbnailBuilder) WithThumbnail(ctx context.Context, t *display.DisplayableThumbnail) display.DisplayableFrameBuilder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithThumbnail", ctx, t)
	ret0, _ := ret[0].(display.DisplayableFrameBuilder)
	return ret0
}

// WithThumbnail indicates an expected call of WithThumbnail.
func (mr *MockThumbnailBuilderMockRecorder) WithThumbnail(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithThumbnail", reflect.TypeOf((*MockThumbnailBuilder)(nil).WithThumbnail), ctx, t)
}

// MockDisplayableFrameBuilder is a mock of DisplayableFrameBuilder interface.
type MockDisplayableFrameBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockDisplayableFrameBuilderMockRecorder
	isgomock struct{}
}

// MockDisplayableFrameBuilderMockRecorder is the mock recorder for MockDisplayableFrameBuilder.
type MockDisplayableFrameBuilderMockRecorder struct {
	mock *MockDisplayableFrameBuilder
}

// NewMockDisplayableFrameBuilder creates a new mock instance.
func NewMockDisplayableFrameBuilder(ctrl *gomock.Controller) *MockDisplayableFrameBuilder {
	mock := &MockDisplayableFrameBuilder{ctrl: ctrl}
	mock.recorder = &MockDisplayableFrameBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisplayableFrameBuilder) EXPECT() *MockDisplayableFrameBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockDisplayableFrameBuilder) Build() (display.DisplayableFrame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build")
	ret0, _ := ret[0].(display.DisplayableFrame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockDisplayableFrameBuilderMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockDisplayableFrameBuilder)(nil).Build))
}
