// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/display (interfaces: Builder)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/builder_mock.go -package=display_test github.com/ma-tf/meta1v/internal/service/display Builder
//

// Package display_test is a generated GoMock package.
package display_test

import (
	context "context"
	reflect "reflect"

	display "github.com/ma-tf/meta1v/internal/service/display"
	records "github.com/ma-tf/meta1v/pkg/records"
	gomock "go.uber.org/mock/gomock"
)

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
	isgomock struct{}
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder {
	mock := &MockBuilder{ctrl: ctrl}
	mock.recorder = &MockBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockBuilder) Build(ctx context.Context, efrm records.EFRM, thumbnail *display.DisplayableThumbnail, strict bool) (display.DisplayableFrame, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", ctx, efrm, thumbnail, strict)
	ret0, _ := ret[0].(display.DisplayableFrame)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockBuilderMockRecorder) Build(ctx, efrm, thumbnail, strict any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockBuilder)(nil).Build), ctx, efrm, thumbnail, strict)
}
