// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/display (interfaces: DisplayableRollFactory)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/factory_mock.go -package=display_test github.com/ma-tf/meta1v/internal/service/display DisplayableRollFactory
//

// Package display_test is a generated GoMock package.
package display_test

import (
	reflect "reflect"

	display "github.com/ma-tf/meta1v/internal/service/display"
	records "github.com/ma-tf/meta1v/pkg/records"
	gomock "go.uber.org/mock/gomock"
)

// MockDisplayableRollFactory is a mock of DisplayableRollFactory interface.
type MockDisplayableRollFactory struct {
	ctrl     *gomock.Controller
	recorder *MockDisplayableRollFactoryMockRecorder
	isgomock struct{}
}

// MockDisplayableRollFactoryMockRecorder is the mock recorder for MockDisplayableRollFactory.
type MockDisplayableRollFactoryMockRecorder struct {
	mock *MockDisplayableRollFactory
}

// NewMockDisplayableRollFactory creates a new mock instance.
func NewMockDisplayableRollFactory(ctrl *gomock.Controller) *MockDisplayableRollFactory {
	mock := &MockDisplayableRollFactory{ctrl: ctrl}
	mock.recorder = &MockDisplayableRollFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisplayableRollFactory) EXPECT() *MockDisplayableRollFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDisplayableRollFactory) Create(r records.Root) (display.DisplayableRoll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", r)
	ret0, _ := ret[0].(display.DisplayableRoll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDisplayableRollFactoryMockRecorder) Create(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDisplayableRollFactory)(nil).Create), r)
}
