// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/display (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/service_mock.go -package=display_test github.com/ma-tf/meta1v/internal/service/display Service
//

// Package display_test is a generated GoMock package.
package display_test

import (
	context "context"
	io "io"
	reflect "reflect"

	display "github.com/ma-tf/meta1v/internal/service/display"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DisplayCustomFunctions mocks base method.
func (m *MockService) DisplayCustomFunctions(ctx context.Context, w io.Writer, r display.DisplayableRoll) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisplayCustomFunctions", ctx, w, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisplayCustomFunctions indicates an expected call of DisplayCustomFunctions.
func (mr *MockServiceMockRecorder) DisplayCustomFunctions(ctx, w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayCustomFunctions", reflect.TypeOf((*MockService)(nil).DisplayCustomFunctions), ctx, w, r)
}

// DisplayFocusingPoints mocks base method.
func (m *MockService) DisplayFocusingPoints(ctx context.Context, w io.Writer, r display.DisplayableRoll) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayFocusingPoints", ctx, w, r)
}

// DisplayFocusingPoints indicates an expected call of DisplayFocusingPoints.
func (mr *MockServiceMockRecorder) DisplayFocusingPoints(ctx, w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayFocusingPoints", reflect.TypeOf((*MockService)(nil).DisplayFocusingPoints), ctx, w, r)
}

// DisplayFrames mocks base method.
func (m *MockService) DisplayFrames(ctx context.Context, w io.Writer, r display.DisplayableRoll) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayFrames", ctx, w, r)
}

// DisplayFrames indicates an expected call of DisplayFrames.
func (mr *MockServiceMockRecorder) DisplayFrames(ctx, w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayFrames", reflect.TypeOf((*MockService)(nil).DisplayFrames), ctx, w, r)
}

// DisplayRoll mocks base method.
func (m *MockService) DisplayRoll(ctx context.Context, w io.Writer, r display.DisplayableRoll) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayRoll", ctx, w, r)
}

// DisplayRoll indicates an expected call of DisplayRoll.
func (mr *MockServiceMockRecorder) DisplayRoll(ctx, w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayRoll", reflect.TypeOf((*MockService)(nil).DisplayRoll), ctx, w, r)
}

// DisplayThumbnails mocks base method.
func (m *MockService) DisplayThumbnails(ctx context.Context, w io.Writer, r display.DisplayableRoll) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisplayThumbnails", ctx, w, r)
}

// DisplayThumbnails indicates an expected call of DisplayThumbnails.
func (mr *MockServiceMockRecorder) DisplayThumbnails(ctx, w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayThumbnails", reflect.TypeOf((*MockService)(nil).DisplayThumbnails), ctx, w, r)
}
