version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go run internal/tools/docgen/main.go --out ./docs --format markdown
    - go run internal/tools/docgen/main.go --out ./man --format man

builds:
  - id: meta1v
    main: .
    binary: meta1v
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - COPYING
      - README.md
      - docs/**/*
      - man/*.1

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

sboms:
  - artifacts: source
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"

changelog:
  sort: asc
  use: github
  format: "{{.SHA}}: {{.Message}}"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^style:'
      - 'typo'
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: ma-tf
    name: meta1v
  prerelease: auto
  mode: append
  footer: |
    ## Installation

    ### Binary Download
    Download the appropriate binary for your system from the assets below.

    ### Linux/macOS
    ```bash
    # Extract the archive
    tar -xzf meta1v_*_linux_amd64.tar.gz
    
    # Move to a directory in your PATH
    sudo mv meta1v /usr/local/bin/
    
    # Optional: Install man pages
    sudo cp man/*.1 /usr/local/share/man/man1/
    sudo mandb
    ```

    ### Windows
    Extract the zip file and add `meta1v.exe` to your PATH.

    ---

    **Full Changelog**: https://github.com/ma-tf/meta1v/compare/{{ .PreviousTag }}...{{ .Tag }}
