// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/osexec (interfaces: Command,LookPath)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/service_mock.go -package=osexec_test github.com/ma-tf/meta1v/internal/service/osexec Command,LookPath
//

// Package osexec_test is a generated GoMock package.
package osexec_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
	isgomock struct{}
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockCommand) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCommandMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCommand)(nil).Start))
}

// Wait mocks base method.
func (m *MockCommand) Wait() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockCommandMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockCommand)(nil).Wait))
}

// MockLookPath is a mock of LookPath interface.
type MockLookPath struct {
	ctrl     *gomock.Controller
	recorder *MockLookPathMockRecorder
	isgomock struct{}
}

// MockLookPathMockRecorder is the mock recorder for MockLookPath.
type MockLookPathMockRecorder struct {
	mock *MockLookPath
}

// NewMockLookPath creates a new mock instance.
func NewMockLookPath(ctrl *gomock.Controller) *MockLookPath {
	mock := &MockLookPath{ctrl: ctrl}
	mock.recorder = &MockLookPathMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLookPath) EXPECT() *MockLookPathMockRecorder {
	return m.recorder
}

// LookPath mocks base method.
func (m *MockLookPath) LookPath(file string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookPath", file)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookPath indicates an expected call of LookPath.
func (mr *MockLookPathMockRecorder) LookPath(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookPath", reflect.TypeOf((*MockLookPath)(nil).LookPath), file)
}
