// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/csv (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/service_mock.go -package=csv_test github.com/ma-tf/meta1v/internal/service/csv Service
//

// Package csv_test is a generated GoMock package.
package csv_test

import (
	io "io"
	reflect "reflect"

	display "github.com/ma-tf/meta1v/internal/service/display"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ExportCustomFunctions mocks base method.
func (m *MockService) ExportCustomFunctions(w io.Writer, cf display.DisplayableRoll) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportCustomFunctions", w, cf)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportCustomFunctions indicates an expected call of ExportCustomFunctions.
func (mr *MockServiceMockRecorder) ExportCustomFunctions(w, cf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportCustomFunctions", reflect.TypeOf((*MockService)(nil).ExportCustomFunctions), w, cf)
}

// ExportFrames mocks base method.
func (m *MockService) ExportFrames(w io.Writer, f display.DisplayableRoll) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportFrames", w, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportFrames indicates an expected call of ExportFrames.
func (mr *MockServiceMockRecorder) ExportFrames(w, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportFrames", reflect.TypeOf((*MockService)(nil).ExportFrames), w, f)
}

// ExportRoll mocks base method.
func (m *MockService) ExportRoll(w io.Writer, r display.DisplayableRoll) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportRoll", w, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportRoll indicates an expected call of ExportRoll.
func (mr *MockServiceMockRecorder) ExportRoll(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportRoll", reflect.TypeOf((*MockService)(nil).ExportRoll), w, r)
}
