// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/exif (interfaces: ExiftoolCommandFactory)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/factory_mock.go -package=exif_test github.com/ma-tf/meta1v/internal/service/exif ExiftoolCommandFactory
//

// Package exif_test is a generated GoMock package.
package exif_test

import (
	bytes "bytes"
	context "context"
	os "os"
	reflect "reflect"

	osexec "github.com/ma-tf/meta1v/internal/service/osexec"
	gomock "go.uber.org/mock/gomock"
)

// MockExiftoolCommandFactory is a mock of ExiftoolCommandFactory interface.
type MockExiftoolCommandFactory struct {
	ctrl     *gomock.Controller
	recorder *MockExiftoolCommandFactoryMockRecorder
	isgomock struct{}
}

// MockExiftoolCommandFactoryMockRecorder is the mock recorder for MockExiftoolCommandFactory.
type MockExiftoolCommandFactoryMockRecorder struct {
	mock *MockExiftoolCommandFactory
}

// NewMockExiftoolCommandFactory creates a new mock instance.
func NewMockExiftoolCommandFactory(ctrl *gomock.Controller) *MockExiftoolCommandFactory {
	mock := &MockExiftoolCommandFactory{ctrl: ctrl}
	mock.recorder = &MockExiftoolCommandFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExiftoolCommandFactory) EXPECT() *MockExiftoolCommandFactoryMockRecorder {
	return m.recorder
}

// CreateCommand mocks base method.
func (m *MockExiftoolCommandFactory) CreateCommand(ctx context.Context, targetFile string, out *bytes.Buffer, metadata string, rPipe *os.File) osexec.Command {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommand", ctx, targetFile, out, metadata, rPipe)
	ret0, _ := ret[0].(osexec.Command)
	return ret0
}

// CreateCommand indicates an expected call of CreateCommand.
func (mr *MockExiftoolCommandFactoryMockRecorder) CreateCommand(ctx, targetFile, out, metadata, rPipe any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommand", reflect.TypeOf((*MockExiftoolCommandFactory)(nil).CreateCommand), ctx, targetFile, out, metadata, rPipe)
}
