// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/exif (interfaces: ToolRunner)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/runner_mock.go -package=exif_test github.com/ma-tf/meta1v/internal/service/exif ToolRunner
//

// Package exif_test is a generated GoMock package.
package exif_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockToolRunner is a mock of ToolRunner interface.
type MockToolRunner struct {
	ctrl     *gomock.Controller
	recorder *MockToolRunnerMockRecorder
	isgomock struct{}
}

// MockToolRunnerMockRecorder is the mock recorder for MockToolRunner.
type MockToolRunnerMockRecorder struct {
	mock *MockToolRunner
}

// NewMockToolRunner creates a new mock instance.
func NewMockToolRunner(ctrl *gomock.Controller) *MockToolRunner {
	mock := &MockToolRunner{ctrl: ctrl}
	mock.recorder = &MockToolRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolRunner) EXPECT() *MockToolRunnerMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockToolRunner) Run(ctx context.Context, targetFile, metadata string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, targetFile, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockToolRunnerMockRecorder) Run(ctx, targetFile, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockToolRunner)(nil).Run), ctx, targetFile, metadata)
}
