// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/exif (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/service_mock.go -package=exif_test github.com/ma-tf/meta1v/internal/service/exif Service
//

// Package exif_test is a generated GoMock package.
package exif_test

import (
	context "context"
	reflect "reflect"

	records "github.com/ma-tf/meta1v/internal/records"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// WriteEXIF mocks base method.
func (m *MockService) WriteEXIF(ctx context.Context, efrm records.EFRM, targetFile string, strict bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteEXIF", ctx, efrm, targetFile, strict)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteEXIF indicates an expected call of WriteEXIF.
func (mr *MockServiceMockRecorder) WriteEXIF(ctx, efrm, targetFile, strict any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteEXIF", reflect.TypeOf((*MockService)(nil).WriteEXIF), ctx, efrm, targetFile, strict)
}
