// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/cli/exif (interfaces: UseCase)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/usecase_mock.go -package=exif_test github.com/ma-tf/meta1v/internal/cli/exif UseCase
//

// Package exif_test is a generated GoMock package.
package exif_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
	isgomock struct{}
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// ExportExif mocks base method.
func (m *MockUseCase) ExportExif(ctx context.Context, efdFile string, frame int, targetFile string, strict bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportExif", ctx, efdFile, frame, targetFile, strict)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportExif indicates an expected call of ExportExif.
func (mr *MockUseCaseMockRecorder) ExportExif(ctx, efdFile, frame, targetFile, strict any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportExif", reflect.TypeOf((*MockUseCase)(nil).ExportExif), ctx, efdFile, frame, targetFile, strict)
}
