// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/efd (interfaces: RootBuilder)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/builder_mock.go -package=efd_test github.com/ma-tf/meta1v/internal/service/efd RootBuilder
//

// Package efd_test is a generated GoMock package.
package efd_test

import (
	context "context"
	reflect "reflect"

	records "github.com/ma-tf/meta1v/internal/records"
	gomock "go.uber.org/mock/gomock"
)

// MockRootBuilder is a mock of RootBuilder interface.
type MockRootBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockRootBuilderMockRecorder
	isgomock struct{}
}

// MockRootBuilderMockRecorder is the mock recorder for MockRootBuilder.
type MockRootBuilderMockRecorder struct {
	mock *MockRootBuilder
}

// NewMockRootBuilder creates a new mock instance.
func NewMockRootBuilder(ctrl *gomock.Controller) *MockRootBuilder {
	mock := &MockRootBuilder{ctrl: ctrl}
	mock.recorder = &MockRootBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRootBuilder) EXPECT() *MockRootBuilderMockRecorder {
	return m.recorder
}

// AddEFDF mocks base method.
func (m *MockRootBuilder) AddEFDF(ctx context.Context, efdf records.EFDF) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEFDF", ctx, efdf)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddEFDF indicates an expected call of AddEFDF.
func (mr *MockRootBuilderMockRecorder) AddEFDF(ctx, efdf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEFDF", reflect.TypeOf((*MockRootBuilder)(nil).AddEFDF), ctx, efdf)
}

// AddEFRM mocks base method.
func (m *MockRootBuilder) AddEFRM(ctx context.Context, efrm records.EFRM) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddEFRM", ctx, efrm)
}

// AddEFRM indicates an expected call of AddEFRM.
func (mr *MockRootBuilderMockRecorder) AddEFRM(ctx, efrm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEFRM", reflect.TypeOf((*MockRootBuilder)(nil).AddEFRM), ctx, efrm)
}

// AddEFTP mocks base method.
func (m *MockRootBuilder) AddEFTP(ctx context.Context, eftp records.EFTP) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddEFTP", ctx, eftp)
}

// AddEFTP indicates an expected call of AddEFTP.
func (mr *MockRootBuilderMockRecorder) AddEFTP(ctx, eftp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEFTP", reflect.TypeOf((*MockRootBuilder)(nil).AddEFTP), ctx, eftp)
}

// Build mocks base method.
func (m *MockRootBuilder) Build() (records.Root, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build")
	ret0, _ := ret[0].(records.Root)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockRootBuilderMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockRootBuilder)(nil).Build))
}
