// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/efd (interfaces: Parser)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/parser_mock.go -package=efd_test github.com/ma-tf/meta1v/internal/service/efd Parser
//

// Package efd_test is a generated GoMock package.
package efd_test

import (
	context "context"
	io "io"
	reflect "reflect"

	records "github.com/ma-tf/meta1v/pkg/records"
	gomock "go.uber.org/mock/gomock"
)

// MockParser is a mock of Parser interface.
type MockParser struct {
	ctrl     *gomock.Controller
	recorder *MockParserMockRecorder
	isgomock struct{}
}

// MockParserMockRecorder is the mock recorder for MockParser.
type MockParserMockRecorder struct {
	mock *MockParser
}

// NewMockParser creates a new mock instance.
func NewMockParser(ctrl *gomock.Controller) *MockParser {
	mock := &MockParser{ctrl: ctrl}
	mock.recorder = &MockParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParser) EXPECT() *MockParserMockRecorder {
	return m.recorder
}

// ParseEFDF mocks base method.
func (m *MockParser) ParseEFDF(ctx context.Context, data []byte) (records.EFDF, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseEFDF", ctx, data)
	ret0, _ := ret[0].(records.EFDF)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseEFDF indicates an expected call of ParseEFDF.
func (mr *MockParserMockRecorder) ParseEFDF(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseEFDF", reflect.TypeOf((*MockParser)(nil).ParseEFDF), ctx, data)
}

// ParseEFRM mocks base method.
func (m *MockParser) ParseEFRM(ctx context.Context, data []byte) (records.EFRM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseEFRM", ctx, data)
	ret0, _ := ret[0].(records.EFRM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseEFRM indicates an expected call of ParseEFRM.
func (mr *MockParserMockRecorder) ParseEFRM(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseEFRM", reflect.TypeOf((*MockParser)(nil).ParseEFRM), ctx, data)
}

// ParseEFTP mocks base method.
func (m *MockParser) ParseEFTP(ctx context.Context, data []byte) (records.EFTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseEFTP", ctx, data)
	ret0, _ := ret[0].(records.EFTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseEFTP indicates an expected call of ParseEFTP.
func (mr *MockParserMockRecorder) ParseEFTP(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseEFTP", reflect.TypeOf((*MockParser)(nil).ParseEFTP), ctx, data)
}

// ParseRaw mocks base method.
func (m *MockParser) ParseRaw(ctx context.Context, r io.Reader) (records.Raw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRaw", ctx, r)
	ret0, _ := ret[0].(records.Raw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseRaw indicates an expected call of ParseRaw.
func (mr *MockParserMockRecorder) ParseRaw(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRaw", reflect.TypeOf((*MockParser)(nil).ParseRaw), ctx, r)
}
