// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/efd (interfaces: Reader)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/reader_mock.go -package=efd_test github.com/ma-tf/meta1v/internal/service/efd Reader
//

// Package efd_test is a generated GoMock package.
package efd_test

import (
	context "context"
	io "io"
	reflect "reflect"

	records "github.com/ma-tf/meta1v/internal/records"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// ReadEFDF mocks base method.
func (m *MockReader) ReadEFDF(ctx context.Context, data []byte) (records.EFDF, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEFDF", ctx, data)
	ret0, _ := ret[0].(records.EFDF)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadEFDF indicates an expected call of ReadEFDF.
func (mr *MockReaderMockRecorder) ReadEFDF(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEFDF", reflect.TypeOf((*MockReader)(nil).ReadEFDF), ctx, data)
}

// ReadEFRM mocks base method.
func (m *MockReader) ReadEFRM(ctx context.Context, data []byte) (records.EFRM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEFRM", ctx, data)
	ret0, _ := ret[0].(records.EFRM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadEFRM indicates an expected call of ReadEFRM.
func (mr *MockReaderMockRecorder) ReadEFRM(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEFRM", reflect.TypeOf((*MockReader)(nil).ReadEFRM), ctx, data)
}

// ReadEFTP mocks base method.
func (m *MockReader) ReadEFTP(ctx context.Context, data []byte) (records.EFTP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEFTP", ctx, data)
	ret0, _ := ret[0].(records.EFTP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadEFTP indicates an expected call of ReadEFTP.
func (mr *MockReaderMockRecorder) ReadEFTP(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEFTP", reflect.TypeOf((*MockReader)(nil).ReadEFTP), ctx, data)
}

// ReadRaw mocks base method.
func (m *MockReader) ReadRaw(ctx context.Context, r io.Reader) (records.Raw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadRaw", ctx, r)
	ret0, _ := ret[0].(records.Raw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadRaw indicates an expected call of ReadRaw.
func (mr *MockReaderMockRecorder) ReadRaw(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadRaw", reflect.TypeOf((*MockReader)(nil).ReadRaw), ctx, r)
}
