// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/service/efd (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/service_mock.go -package=efd_test github.com/ma-tf/meta1v/internal/service/efd Service
//

// Package efd_test is a generated GoMock package.
package efd_test

import (
	context "context"
	io "io"
	reflect "reflect"

	records "github.com/ma-tf/meta1v/pkg/records"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// RecordsFromFile mocks base method.
func (m *MockService) RecordsFromFile(ctx context.Context, r io.Reader) (records.Root, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordsFromFile", ctx, r)
	ret0, _ := ret[0].(records.Root)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordsFromFile indicates an expected call of RecordsFromFile.
func (mr *MockServiceMockRecorder) RecordsFromFile(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordsFromFile", reflect.TypeOf((*MockService)(nil).RecordsFromFile), ctx, r)
}
