// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ma-tf/meta1v/internal/records (interfaces: ThumbnailFactory)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/thumbnail_factory_mock.go -package=records_test github.com/ma-tf/meta1v/internal/records ThumbnailFactory
//

// Package records_test is a generated GoMock package.
package records_test

import (
	image "image"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockThumbnailFactory is a mock of ThumbnailFactory interface.
type MockThumbnailFactory struct {
	ctrl     *gomock.Controller
	recorder *MockThumbnailFactoryMockRecorder
	isgomock struct{}
}

// MockThumbnailFactoryMockRecorder is the mock recorder for MockThumbnailFactory.
type MockThumbnailFactoryMockRecorder struct {
	mock *MockThumbnailFactory
}

// NewMockThumbnailFactory creates a new mock instance.
func NewMockThumbnailFactory(ctrl *gomock.Controller) *MockThumbnailFactory {
	mock := &MockThumbnailFactory{ctrl: ctrl}
	mock.recorder = &MockThumbnailFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThumbnailFactory) EXPECT() *MockThumbnailFactoryMockRecorder {
	return m.recorder
}

// NewRGBA mocks base method.
func (m *MockThumbnailFactory) NewRGBA(rect image.Rectangle) *image.RGBA {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRGBA", rect)
	ret0, _ := ret[0].(*image.RGBA)
	return ret0
}

// NewRGBA indicates an expected call of NewRGBA.
func (mr *MockThumbnailFactoryMockRecorder) NewRGBA(rect any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRGBA", reflect.TypeOf((*MockThumbnailFactory)(nil).NewRGBA), rect)
}
